apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cepsi241g-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:9984586d00f1431efb06bf6f0c58905fd5a7c191@sha256:5f23b751dc84a6fe4eed03332eb48e333ca9478a26b29a13902e9e5d09feda94
          name: container-image
